version: '3'
services:

  client:
    build:
      context: ./
      dockerfile: dockerfile
      args:
        AIOHTTP: ${AIOHTTP:-3.9.3}
        PYTHON: ${PYTHON:-3.10}
        FLAVOR: ${FLAVOR:-buster}
    environment:
      - EVENTLOOP=${EVENTLOOP-asyncio}
      # - CT_TOTAL=${CT_TOTAL:-1}
      # - CT_CONNECT=${CT_CONNECT:-0.5}
      # - CT_SOCK_CONNECT=${CT_SOCK_CONNECT:-0.5}
      - CT_TOTAL=${CT_TOTAL:-0}
      - CT_CONNECT=${CT_CONNECT:-0}
      - CT_SOCK_CONNECT=${CT_SOCK_CONNECT:-0}
      - CEIL_THRESHOLD=${CEIL_THRESHOLD:-0}
      - CONCURRENCY=${CONCURRENCY:-500}
      - MODE=${MODE:-concurrency}
      - SERVER=${SERVER:-proxied}
    volumes:
      - ./tcpdump:/tcpdump
  proxy:
    image: nginx
    volumes:
      - ./proxy_nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 12000:80

  proxied:
    image: nginx
    volumes:
      - ./proxied_nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 11000:80
